title: Muhammed Yılmaz
tagline: Vibe-Blog
description: >-
  A blog about posts of the topics of the videos I uploaded.
author: Muhammed Yılmaz
email: muhammedyilmazyil.com
url: muhammedyilmaz.blog   # <-- change to your actual domain, no trailing slash
baseurl: ""

# Markdown / build settings — leave these alone
markdown: kramdown
permalink: /:year/:month/:day/:title/
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
